#Cas pratique : Regression Logistique Binaire

#Monter le drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#Importation des bibliotheques

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import warnings
import pickle
import chardet
#metrics
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve, precision_recall_curve
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
from sklearn.metrics import confusion_matrix, log_loss
from sklearn.model_selection import learning_curve

#Afficher le Dataset Forest fire

In [3]:
warnings.filterwarnings("ignore")

with open('/content/drive/MyDrive/Colab Notebooks/Forest_fire.csv', 'rb') as f:
    result = chardet.detect(f.read())  # or readline if the file is large
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Forest_fire.csv', encoding=result['encoding'])


data.head(10)

Area  Oxygen  Temperature  Humidity  Fire Occurrence
0     Brésil      40           45        20                1
1      Japon      50           30        10                1
2  Allemagne      10           20        70                0
3       Inde      60           45        70                1
4     Égypte      30           48        10                1
5  Australie      50           15        30                0
6    Mexique       5           35        35                0
7     Russie       5           20        70                0
8    Espagne      60           32        19                1
9    Turquie      30           50        45                1

#Separer les X des y

In [ ]:
data = np.array(data)

X = data[1:, 1:-1]
y = data[1:, -1]
y = y.astype('int')
X = X.astype('int')

#Split les donnees en Training et Testing

In [ ]:
# print(X,y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((26, 3), (12, 3), (26,), (12,))

#Creation et Entrainnement du modele LogisticRegression

In [ ]:
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

array([[0.14459396, 0.85540604]])

In [ ]:
y_pred = log_reg.predict(X_test)
y_pred

array([1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1])

#Afficharge des metrics

In [ ]:
print('Precision: %.3f' % precision_score(y_test, y_pred))
print('Recall: %.3f' % recall_score(y_test, y_pred))
print('Accuracy: %.3f' % accuracy_score(y_test, y_pred))
print('F1 Score: %.3f' % f1_score(y_test, y_pred))


Precision: 1.000
Recall: 1.000
Accuracy: 1.000
F1 Score: 1.000


In [ ]:
inputt=[int(x) for x in "45 32 60".split(' ')]
final=[np.array(inputt)]

b = log_reg.predict_proba(final)
b

array([[0.14459396, 0.85540604]])

#Affichage des probabilites du testing

In [ ]:
prediction = log_reg.predict_proba(X_test)
prediction

array([[5.85911092e-08, 9.99999941e-01],
       [8.16880845e-05, 9.99918312e-01],
       [7.60303011e-01, 2.39696989e-01],
       [9.12010869e-05, 9.99908799e-01],
       [9.99999949e-01, 5.12780338e-08],
       [1.32391727e-06, 9.99998676e-01],
       [9.99999391e-01, 6.09412394e-07],
       [5.71219898e-01, 4.28780102e-01],
       [9.99999809e-01, 1.91167368e-07],
       [2.63321295e-06, 9.99997367e-01],
       [9.99999891e-01, 1.08587586e-07],
       [7.97649662e-06, 9.99992024e-01]])

In [ ]:
df_prediction = pd.DataFrame({'Actual': y_test, 'Predicted':y_pred})
df_prediction

Actual  Predicted
0        1          1
1        1          1
2        0          0
3        1          1
4        0          0
5        1          1
6        0          0
7        0          0
8        0          0
9        1          1
10       0          0
11       1          1

#Calculer la fonction de coût (log loss) sur l'ensemble de test

In [ ]:
# Calculer la fonction de coût (log loss) sur l'ensemble de test
cost = log_loss(y_test, log_reg.predict_proba(X_test))

# Affichage du résultat
print(f"Fonction de coût (log loss) : {cost}")

Fonction de coût (log loss) : 0.06951709244916064


#Evaluation du modole de regression logistique

In [ ]:
#Create classification report
from sklearn.metrics import classification_report

class_report=classification_report(y_test, y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         6

    accuracy                           1.00        12
   macro avg       1.00      1.00      1.00        12
weighted avg       1.00      1.00      1.00        12



In [ ]:
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

Confusion Matrix:
 [[6 0]
 [0 6]]


In [ ]:
# Extract the true positive, true negative, false positive, and false negative values from the confusion matrix
tn, fp, fn, tp = conf_matrix.ravel()

# Print the true positive, true negative, false positive, and false negative values
print("True Positive (TP): ", tp)
print("True Negative (TN): ", tn)
print("False Positive (FP): ", fp)
print("False Negative (FN): ", fn)

True Positive (TP):  6
True Negative (TN):  6
False Positive (FP):  0
False Negative (FN):  0
